version: "3.9"
services:
  notebook:
    build:
      context: ./
    command: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/work/
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./notebook:/work/notebook
      - ./dataset:/work/dataset
      - ./submits:/work/submits
      - ./src:/work/src
